[versions]
minestom = "79716ab749"
adventure = "4.17.0"
kotlin-reflect = "2.0.0"
kotlinx-coroutines = "1.9.0-RC"
kotlinx-serialization = "1.7.1"
kotest = "5.9.1"

shadow = "8.1.8"
dokka = "1.9.20"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

[libraries]
minestom = { group = "net.minestom", name = "minestom-snapshots", version.ref = "minestom" }
adventure-nbt = { group = "net.kyori", name = "adventure-nbt", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin-reflect" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotest-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-junit = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

[bundles]
test = ["kotest-core", "kotest-junit"]