name: Publish project to Maven repository
# Publish when releasing a new version
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publish
        env:
          MAVEN_NAME: ${{ secrets.REPOSILITE_NAME }}
          MAVEN_SECRET: ${{ secrets.REPOSILITE_SECRET }}